version: "3.7"
services:
  api:
    container_name: api
    restart: always
    build: ./api
    volumes: 
      - ./api:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
# Volume has to be defined
volumes: 
  data: