version: "3.7"
services:
  api:
    container_name: api
    restart: always
    build: ./api
    volumes: 
      - ./api:/usr/src/app
    ports:
      - "8080:8080"
    external_links:
      - app
      - mongo
  app:
    container_name: app
    restart: always
    build: ./app
    volumes: 
      - ./app:/usr/src/app
    ports:
      - "4200:4200"
    external_links:
      - api
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
# Volume has to be defined
volumes: 
  data: